### ISSUE TITLE
Regarding download_models module

### ISSUE THREAD

**Issue by erhanbicerr** [AffectAnalysisGroup/PyAFAR#5]
Hello,
Firstly, thank you for providing such a valuable tool, especially for infant studies :pray:. 

I would like to offer a functionality if it has not been in your agenda: When downloading models with "download_models", my internet connection got disconnected, and models could not be installed. When I try to re-execute the module, it is not downloading the AU models as they have been downloaded before. Yet, I'm having errors in the interface as the AU models are not available. So, maybe forcing the module to download the models can be a good feature to think on. Thanks!

**Comment by bmaneesh** [comment]
Thank you @erhanbicerr, for the feedback. It's a good idea to enable a forced download for such cases. We will add this in our next release. Meanwhile, have you fixed the download problem or are you still working on it?
