### ISSUE TITLE
 tensorflow version in PyAFAR_CPU-3.0-py3-none-any.whl

### ISSUE THREAD

**Issue by florianbednarski** [AffectAnalysisGroup/PyAFAR#6]
Kia ora koutou from Auckland,

we are tryning to use PyAFAR but are stuck at the installation step 3. pip install PyAFAR_CPU-3.0-py3-none-any.whl with the following error:

ERROR: Could not find a version that satisfies the requirement tensorflow==2.12 (from pyafar-cpu) (from versions: 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0, 2.13.1, 2.14.0rc0, 2.14.0rc1, 2.14.0, 2.14.1, 2.15.0rc0, 2.15.0rc1, 2.15.0, 2.15.1, 2.16.0rc0, 2.16.1, 2.17.0rc0)
ERROR: No matching distribution found for tensorflow==2.12

It appears tensorflow==2.12 is not supported anymore. Can you help with this?

**Comment by bmaneesh** [comment]
@florianbednarski are you using the exact recommended python version and installation instructions? If your python version is different, the dependency versions will also change. So, your versions for tensorflow start with 2.13 instead.

I tried it today on Ubuntu and the installation worked fine. Also, pip did not deprecate [tensorflow 2.12.0](https://pypi.org/project/tensorflow/2.12.0/) version. You should not have any trouble.

**Comment by florianbednarski** [comment]
@bmaneesh thank you for the fast response. This was oversight on my end, I build a venv with the wrong python version.
