### ISSUE TITLE
ERROR: No matching distribution found for PySimpleGUI==4.60.5

### ISSUE THREAD

**Issue by raihanba13** [AffectAnalysisGroup/PyAFAR#7]
Hello,

Since the change to PySimpleGUI's subscription model, they don't have any versions less than 5. From version 5, it offers a hobbyist version, though. They removed all the old LGPL versions from PyPI. You may find more information in this thread:  https://www.reddit.com/r/Python/comments/1d8d4iv/psa_pysimplegui_has_deleted_almost_all_old_lgpl/
Please update your dependencies.
Thanks for your kind attention.

**Comment by adidust4** [comment]
Hi, 

How would you recommend getting around this dependency error? Thank you.

**Comment by Ntweat** [comment]
Thank you @raihanba13  and @adidust4 for making us aware of the issue. We will start looking into it and update once we have a solution we will keep this thread open till it is resolved.

**Comment by raihanba13** [comment]
@adidust4 I had Docker Image so I could reuse it. 

You can try to use this library, https://github.com/spyoungtech/FreeSimpleGUI

May be edit the source code of PyAFAR and make this change. Hope this helps.

**Comment by Ntweat** [comment]
We have made plans to switch to FreeSimpleGUI. We will be releasing the new binary soon.

We will release it only after internal reviews and testing.

**Comment by bmaneesh** [comment]
Hi, we updated PyAFAR with a new release and you should no longer get the PySimpleGUI error. Please let us know if you are having any trouble. Installation instructions remain the same with our latest v4.0.0 release.
