### ISSUE TITLE
 Could not find a version that satisfies the requirement tensorflow==2.12 (

### ISSUE THREAD

**Issue by rahulnoobcoder** [AffectAnalysisGroup/PyAFAR#8]
(ven) PS D:\internship\pyafr> pip install PyAFAR_CPU-3.0-py3-none-any.whl                         
Processing d:\internship\pyafr\pyafar_cpu-3.0-py3-none-any.whl
INFO: pip is looking at multiple versions of pyafar-cpu to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement tensorflow==2.12 (from pyafar-cpu) (from versions: 2.16.0rc0, 2.16.1, 2.16.2, 2.17.0rc0, 2.17.0rc1, 2.17.0)
ERROR: No matching distribution found for tensorflow==2.12

**Comment by jhdjurhuus** [comment]
I have the same issue, I am using MacOS.

**Comment by jhdjurhuus** [comment]
I am using Anaconda on MacOS 15 and I managed to fix this in my case by using the anaconda-navigator to install TensorFlow 2.12 within the pyafar environment I had created in the terminal.

**Comment by bmaneesh** [comment]
Hi, we updated PyAFAR with a new release. Please reopen the issue if you still encounter the problem using the latest release.
